### ISSUE TITLE
RSGallery2 database issue

### ISSUE THREAD

**Issue by 60600009** [RSGallery2/RSGallery2_J4#1]
I have RSGallery2 installed and it is working OK but Joomla is showing the following error.

From System->Maintenance->Database 2
2 Problems
- Database version (5.0.11.13) does not match manifest version (5.0.11).
- Table 'jos_rsgallery2_comments' has the wrong type or attributes for column 'datetime' with type datetime. (From file 1.13.2.sql.) 
- 28 database changes were checked.
- 34 database changes did not alter table structure and were skipped. 

RSGallery2 	5.0.12.01
Joomla		4.4.5
Apache 		2.4.51
PHP 		8.2.2
Windows 	10

**Comment by ThomasFinnern** [comment]
I will check for it and fix it
* Database version (5.0.11.13) does not match ...
  ==> This is an Info . It will have no  effect on the function
* Table 'jos_rsgallery2_comments' has the wrong type
   ==> As long as you do not allow comments it has no effect. Otherwise sorry comments are not not supported.
